#!/bin/bash
#SBATCH --job-name=qualindex_nelms_2019         # Job name
#SBATCH --partition=batch             # Partition (queue) name
#SBATCH --ntasks=1                    # Run on a single CPU
#SBATCH --mem=30gb                     # Job memory request
#SBATCH --time=02:00:00               # Time limit hrs:min:sec
#SBATCH --output=nelms2019.%j.out    # Standard output log
#SBATCH --error=nelms2019.%j.err     # Standard error log

module spider FastQC/0.11.9-Java-11

fastqc SRR7989734_1.fastq.gz
fastqc SRR7989735_1.fastq.gz
fastqc SRR7989736_1.fastq.gz
fastqc SRR7989737_1.fastq.gz
fastqc SRR7989738_1.fastq.gz
fastqc SRR7989739_1.fastq.gz
fastqc SRR7989740_1.fastq.gz

