#!/bin/bash
#SBATCH --job-name=download_nelms_2019         # Job name
#SBATCH --partition=batch             # Partition (queue) name
#SBATCH --ntasks=1                    # Run on a single CPU
#SBATCH --mem=50gb                     # Job memory request
#SBATCH --time=02:00:00               # Time limit hrs:min:sec
#SBATCH --output=nelms2019.%j.out    # Standard output log
#SBATCH --error=nelms2019.%j.err     # Standard error log

module load SRA-Toolkit/2.11.1-centos_linux64

fastq-dump --split-files --gzip SRR7989734
fastq-dump --split-files --gzip SRR7989735
fastq-dump --split-files --gzip SRR7989736
fastq-dump --split-files --gzip SRR7989737
fastq-dump --split-files --gzip SRR7989738
fastq-dump --split-files --gzip SRR7989739
fastq-dump --split-files --gzip SRR7989740
